"""added transfer limit for rounds

Revision ID: a0b480e53467
Revises: bcf3bb8f5f91
Create Date: 2025-10-08 12:05:11.484500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b480e53467'
down_revision: Union[str, Sequence[str], None] = 'bcf3bb8f5f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_round', sa.Column('transfer_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_round', 'transfer_limit')
    # ### end Alembic commands ###
