"""Adding position to squadplayer

Revision ID: a6e343bccc5d
Revises: f4080bf1e8c0
Create Date: 2025-10-07 16:52:40.356910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e343bccc5d'
down_revision: Union[str, Sequence[str], None] = 'f4080bf1e8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad_player', sa.Column('squad_position', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad_player', 'squad_position')
    # ### end Alembic commands ###
