"""Initial migration 2: user and league tables

Revision ID: c12700715a3c
Revises: 27644ddf57f1
Create Date: 2025-10-04 11:40:37.518895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12700715a3c'
down_revision: Union[str, Sequence[str], None] = '27644ddf57f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('join_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_join_code'), 'league', ['join_code'], unique=True)
    op.create_index(op.f('ix_league_name'), 'league', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_name'), table_name='league')
    op.drop_index(op.f('ix_league_join_code'), table_name='league')
    op.drop_table('league')
    # ### end Alembic commands ###
